[package]
name = "database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "10.0.0"
anyhow = "1.0.58"
nom = "7.1.1"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }